version: '3.4'
services:
  app1: &app
    build: .
    hostname: app1
    environment:
      PORT: 3000
      NODE_ENV: production
      DATABASE: rinha
      DATABASE_USER: postgres
      DATABASE_PASSWORD: 123
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_POOL: 200
    expose:
      - "3000"
    # network_mode: host
    depends_on:
      - postgres
    ulimits:
      nproc: 1000000
      nofile:
        soft: 1000000
        hard: 1000000
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.6GB'
      
  app2:
    <<: *app
    hostname: app2

  postgres:
    image: postgres
    command: postgres -c 'max_connections=450' -c 'log_error_verbosity=terse'
    environment:
      POSTGRES_DB: rinha
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1.5GB'
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.3GB'